### PR TITLE
Fix MessageVerifier to work with new API

### PR DESCRIPTION
**Pull request by zzak**
This API changed in https://github.com/rails/rails/commit/91b2a15 (#47325)

/cc @jonathanhefner

How to reproduce:

```
>> GlobalID::Locator.locate_signed(Company.first.to_sgid(for: :debug), for: :debug)
  Company Load (0.1ms)  SELECT "companies".* FROM "companies" ORDER BY "companies"."id" ASC LIMIT ?  [["LIMIT", 1]]
  Company Load (0.1ms)  SELECT "companies".* FROM "companies" WHERE "companies"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
=> #<Company:0x00000001052f1560 id: 1, name: "nintendo", created_at: Mon, 07 Aug 2023 10:27:45.223195000 UTC +00:00, updated_at: Mon, 07 Aug 2023 10:27:45.223195000 UTC +00:00>
```

Previously, using the JSON method, this would return `nil`.

### CODE REVIEW

**Comment by zzak** [comment]
I should mention this doesn't occur when using other non-JSON message serializers, via:

```
Rails.application.config.active_support.message_serializer = :message_pack
```

The new default `:json_allow_marshal` also returns `nil`.

**Comment by zzak** [comment]
Also found #149 as possibly related, but haven't looked into it much further, could be a red herring.

**Review by jonathanhefner — CHANGES_REQUESTED** [review]
rails/rails@91b2a15e2bb4a8dc974f370bc0bd6b65fb969472 did not change these method names; it just factored them out [into `ActiveSupport::Messages::Codec`](https://github.com/rails/rails/blob/2942958827f1934dfcba284d074e6d61104d3e7c/activesupport/lib/active_support/messages/codec.rb#L25-L33).  The [`sign_encoded` and `extract_encoded` methods](https://github.com/rails/rails/blob/2942958827f1934dfcba284d074e6d61104d3e7c/activesupport/lib/active_support/message_verifier.rb#L309-L329) are different.

The problem here is actually the change of the default serializer from `Marshal` to `JSON` (via rails/rails#42843).  `JSON` does not roundtrip symbols.  So if you change your example to

```ruby
GlobalID::Locator.locate_signed(Company.first.to_sgid(for: "debug"), for: "debug")
```

it will work.  You can even change it to

```ruby
GlobalID::Locator.locate_signed(Company.first.to_sgid(for: :debug), for: "debug")
```

and it will work.

To support symbol purposes for all serializers, we would need to change

https://github.com/rails/globalid/blob/86ddaae0b882505e0a2118ba62300384af5b496c/lib/global_id/signed_global_id.rb#L45

to

```ruby
        metadata['gid'] if pick_purpose(options)&.to_s == metadata['purpose']&.to_s
```

(Note that `ActiveSupport::MessageVerifier` already [does this internally](https://github.com/rails/rails/blob/8ec349dc55dcfb62a2f0547713b776f7035b1732/activesupport/lib/active_support/messages/metadata.rb#L67-L78) when using its `:purpose` option, but `SignedGlobalID` handles purpose itself.)

**Comment by rafaelfranca** [comment]
I'm trying to write a test to reproduce this error and this one always pass.

Am I missing something?

```
  test 'foo' do
    verifier = GlobalID::Verifier.new('muchSECRETsoHIDDEN', serializer: JSON)
    assert_equal Person::Child.new('2'), GlobalID::Locator.locate_signed(Person::Child.new('2').to_sgid(for: :debug, verifier: verifier), for: :debug, verifier: verifier)
  end
```

**Comment by jonathanhefner** [comment]
I was testing with a released version of Global ID.  It looks like this may be fixed on `main` by dc9a6487b3354ae2d2054b5fd5b4e57fbbad97bc and 12f76297c803c658ea2fc684d4336db347a90901, which route verification through `ActiveSupport::MessageVerifier` (which calls `to_s` on the purpose).

**Comment by rafaelfranca** [comment]
Thanks! I just got that. I updated the test and the legacy verifier behavior to make sure this works.

**Pull request closed without merging**
