### PR TITLE
fix extension of readme

### PR DESCRIPTION
**Pull request by y-yagi**
Follow up to 2c1fbfc

### CODE REVIEW

**Comment by y-yagi** [comment]
Hmmm. Test has failed in installation of rack 2.0.1.  I think need to update Travis build matrix.

**Comment by kaspth** [comment]
Ah yeah, let's bump 2.2 to 2.2.4 that should fix that part of the matrix.

Then how do we lock Rack on Ruby 2.1 and earlier?

**Comment by y-yagi** [comment]
In same as [activerecord\-session\_store/\.travis\.yml](https://github.com/rails/activerecord-session_store/blob/master/.travis.yml), I think that it is good to divide Gemfile for each version of Rails.  What do you think?

**Comment by kaspth** [comment]
If Rack is the only misbehaving dependency maybe that's a bit too quick to split them out. Maybe this could be enough?

```ruby
gem 'rack', Gem::Version.new(RUBY_VERSION) >= '2.2.2' ? '~> 2.0' : '~> 1.0'
```

Although that's also hacky. Your call 😁

**Comment by y-yagi** [comment]
Necessary correspondence also about Rails components(`activemodel`, `railties` and maybe other also).  Therefore, I think that trying to corresponding divided gemfile :wink:.   I will create another PR.

**Pull request merged**
