### PR TITLE
Add Ruby 2.4.0 to Traivs CI.

### PR DESCRIPTION
**Pull request by junaruga**
Maybe it's time to add Ruby 2.4.0 to Traivs.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Can you remove Rails 4.1 from the 2.4 tests and make sure 4.2 is using Rails 4.2.8?

**Comment by junaruga** [comment]
@rafaelfranca ok just moment.

**Comment by junaruga** [comment]
@rafaelfranca 
Rails 4.2 tests are not using Rails 4.2.8. they are using 4.2.7.1
https://travis-ci.org/rails/globalid/builds/201138053

4.2.7.1 is latest stable version for 4.2.
https://rubygems.org/gems/rails/versions

**Comment by rafaelfranca** [comment]
You can point to 4-2-stable branch that it is 4.2.8

**Comment by junaruga** [comment]
@rafaelfranca I pointed to 4-2 stable branch. and tests were passed!

**Pull request merged**
